# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file into the container at /app
COPY target/app.jar /app/helloApp.jar

# Expose port 8080 to access the application
EXPOSE 8080

# Command to run the JAR file when the container starts
CMD ["java", "-jar", "helloApp.jar"]
